repos:
  - repo: local
    hooks:
      - id: test-echo
        name: Test echo
        entry: echo "Testing pre-commit hooks"  
        language: system
        pass_filenames: false
        
      # - id: mkdocs-linkcheck
      #   name: Check mkdocs links
      #   entry: mkdocs build --config-file mkdocs-linkcheck.yml
      #   language: system
      #   pass_filenames: false