name: Deploy Water Linked Docs

on:
  push:
    branches:
    - master
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.6
      uses: actions/setup-python@v1
      with:
        python-version: 3.6
    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        python3 -m pip install -r requirements.txt
    - name: Clone waterlinked.github.io
      uses: actions/checkout@v2
      with:
        repository: waterlinked/waterlinked.github.io
        token: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        path: waterlinked.github.io
    - name: Build
      run: |
        cd waterlinked.github.io
        mkdocs gh-deploy --config-file ../mkdocs.yml --remote-branch master
